services:
    subugoe_find.query_service:
        class: Subugoe\FindBundle\Service\QueryService
        arguments: ["%default_query%", "%default_sort%", "%hidden%", "%facets%"]

    Subugoe\FindBundle\Service\QueryService:
        alias: subugoe_find.query_service

    default_controller:
        class: Subugoe\FindBundle\Controller\DefaultController
        autowire: true
        autoconfigure: true

    subugoe_find.search_service:
      class: Subugoe\FindBundle\Service\SearchService
      autowire: true
      autoconfigure: true

    Subugoe\FindBundle\Service\SearchService:
      alias: subugoe_find.search_service
